---
# This role contains task for configuring virtual drives

- name: set password policy
  cisco_imc_password_policy:
    strong_password: "enabled"
    ip: "{{ imc_ip }}"
    username: "{{ imc_username }}"
    password: "{{ imc_password }}"


- name: create local user
  cisco_imc_user:
    name: "jdoe"
    pwd: "G3N3-123"
    priv: "admin"
    state: "present"
    ip: "{{ imc_ip }}"
    username: "{{ imc_username }}"
    password: "{{ imc_password }}"


- name: delete local user
  cisco_imc_user:
    name: "jdoe"
    priv: "admin"
    state: "absent"
    ip: "{{ imc_ip }}"
    username: "{{ imc_username }}"
    password: "{{ imc_password }}"


- name: reset password policy
  cisco_imc_password_policy:
    strong_password: "disabled"
    ip: "{{ imc_ip }}"
    username: "{{ imc_username }}"
    password: "{{ imc_password }}"


